/*
 * generated by Xtext 2.21.0
 */
package smitey;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MathinterpreterStandaloneSetup extends MathinterpreterStandaloneSetupGenerated {

	public static void doSetup() {
		new MathinterpreterStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
